### PR TITLE
Added visual code coverage for testing using simplecov

### PR DESCRIPTION
**Pull request by monkey670**
## Pull Request Checklist

**Is this in reference to an existing issue?** No

#### General

- [ ] Update Changelog following the conventions laid out [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [X] RuboCop passes

- [X] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose
SimpleCov (https://github.com/colszowka/simplecov) is a ruby code coverage tool useful for testing locally and as part of a CI/CD pipeline. It also integrates with codeclimate nicely but it will need configuring using the .travis file and a test token found in the project on codeclimate.

```
env:
  global:
    - CC_TEST_REPORTER_ID=<Add Your Test Coverage Token from CodeClimate here>
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
```

### CODE REVIEW

**Comment by majormoses** [comment]
Thanks for your contribution to Sensu plugins! Without people like you submitting PRs we couldn't run the project. I will review it shortly.

**Comment by majormoses** [comment]
I know we used to use code climate a long time ago and then stopped. @eheydrick was it just an extra thing to manage? This plugin does have fairly decent unit test coverage so we could try it again with this repo.

**Comment by eheydrick** [comment]
Codeclimate did a coverage report but it wasn't overly useful because most plugins didn't have any tests at all. Now that code coverage is improving I think it would be good to track code quality - either with simplecov or codeclimate or a combination of the 2.

**Comment by majormoses** [comment]
Thanks for the push, will get that set up when one of us has the time.

**Pull request merged**
