### PR TITLE
updates metrics plugins overview and per queue

### PR DESCRIPTION
**Pull request by jaimegago**

### CODE REVIEW

**Comment by mattyjones** [comment]
@jaimegago  You probably need to rebase this and take a look at the travis output.

Thanks!

**Comment by jaimegago** [comment]
@mattyjones I fixed most of the travis issues (still working on one) did a rebase to squash my commit, I was expecting to see a Travis rubocop check kick in, instead got a merge conflict. I'm about to kill this PR and create a new one, let me know if there is another way.

**Comment by analytically** [comment]
Yeah a new PR is perhaps best.

**Comment by mattyjones** [comment]
@jaimegago  Any progress with this?

**Comment by jaimegago** [comment]
@mattyjones sorry, haven't abandoned it, it's just that one of my colleagues at work has written a RMQ that just iterates and grab all the stats recursively as opposed to hard coded like in this one. I need to review the new plugin and submit it. I'll close this PR in the meantime.

**Pull request closed without merging**
