### PR TITLE
dont assume people want hostname in the scheme

### PR DESCRIPTION
**Pull request by jmickle**

### CODE REVIEW

**Comment by analytically** [comment]
We use the hostname in most of the plugins, for good reason. I'm :-1: on this PR, @mattyjones?

**Comment by jmickle** [comment]
I am not sure who you mean by we but anyone using a hosted graphing system like librato end up having to roll their own package. because this results in no way to zero out the socket.gethostname param

**Comment by jmickle** [comment]
also you shouldnt assume your infra design is the "right solution" for other people

**Comment by eheydrick** [comment]
Can't you just override the scheme with whatever you want? That's why the scheme parameter is there. I use influxdb and setting the prefix to the hostname also does not make sense so I override it.

**Comment by jmickle** [comment]
ended up writing a different collector for rabbitmq, feel free to close

**Pull request closed without merging**
