### PR TITLE
Move duplicated code to libraries

### PR DESCRIPTION
**Pull request by rthouvenin**
## Pull Request Checklist

This is a starting point to implement #65. Adds rspec tests to one check and two metrics, and moves common code away from these check and metrics into a common module.

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass

### CODE REVIEW

**Comment by majormoses** [comment]
https://travis-ci.org/sensu-plugins/sensu-plugins-rabbitmq/jobs/263009237#L257 can you fix this up?

**Comment by rthouvenin** [comment]
@majormoses Sure, not sure why this error doesn't show on my local clone...
But while fixing I realised I use a method (`Hash#dig`) that exists only from Ruby 2.3. Is it acceptable to add a dependency to https://github.com/Invoca/ruby_dig so that the rabbitmq plugin is still compatible with Ruby >= 2.0?

**Comment by majormoses** [comment]
Ff that gem is not compatible with < 2.3 then we should not use it until ruby 2.2 is EOL. Our stance on ruby version support is here: https://github.com/sensu-plugins/documentation/blob/master/docs/FAQ.md#what-is-the-policy-on-supporting-end-of-lifeeol-ruby-versions.

**Comment by rthouvenin** [comment]
Sorry, I think my explanation was confusing. I wrote the code using the `dig` method of the `Hash` class that appeared in Ruby 2.3. Since we should support Ruby >= 2.0, I am suggesting adding the gem ruby_dig that is no-op on Ruby >= 2.3, and adds the `dig` method on Ruby < 2.3.

**Comment by majormoses** [comment]
I am coming back from sensu summit, I will get to this next week.

**Comment by majormoses** [comment]
the errors are likely because you are using `require_relative` which was removed in ruby 1.9. You should just use require instead.

**Comment by majormoses** [comment]
When I pulled this I get this locally:
```
$ bundle install
The latest bundler is 1.15.3, but you are currently running 1.15.1.
To update, run `gem install bundler`

[!] There was an error parsing `Gemfile`: 
[!] There was an error while loading `sensu-plugins-rabbitmq.gemspec`: cannot load such file -- carrot-top
Does it try to require a relative path? That's been removed in Ruby 1.9. Bundler cannot continue.

 #  from /tmp/sensu-plugins-rabbitmq/sensu-plugins-rabbitmq.gemspec:5
 #  -------------------------------------------
 #  require 'date'
 >  require_relative 'lib/sensu-plugins-rabbitmq'
 #  
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /tmp/sensu-plugins-rabbitmq/Gemfile:4
 #  -------------------------------------------
 #  # Specify your gem's dependencies in sensu-plugins-rabbitmq.gemspec
 >  gemspec
 #  -------------------------------------------
```

**Comment by majormoses** [comment]
I got it to install the deps after changing this:
```
$ git diff
diff --git a/sensu-plugins-rabbitmq.gemspec b/sensu-plugins-rabbitmq.gemspec
index cc4c705..7bd97b1 100644
--- a/sensu-plugins-rabbitmq.gemspec
+++ b/sensu-plugins-rabbitmq.gemspec
@@ -2,7 +2,7 @@ lib = File.expand_path('../lib', __FILE__)
 $LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
 
 require 'date'
-require_relative 'lib/sensu-plugins-rabbitmq'
+require 'sensu-plugins-rabbitmq/version'
 
 Gem::Specification.new do |s|
   s.authors                = ['Sensu-Plugins and contributors']
```

**Comment by rthouvenin** [comment]
Sorry that I made you lose time on this. I actually had solved the issue, but didn't push the fix because of the problem with the `dig` method. Now I pushed it, so the unit tests should break and show the problem and hopefully it will be clearer.

**Comment by majormoses** [comment]
@rthouvenin from what I see you might be able to get it to work nowe by including `ruby_dig` in the gemspec and in the required files.

**Comment by rthouvenin** [comment]
OK, yes that was my question: can I add a dependency, as I didn't know if there is any policy for that.
Will do that.

**Comment by majormoses** [comment]
While we prefer to keep the dependencies small I am not opposed to bringing in new dependencies but they must be weighed for things like do they require a c compiler. Generally if it does not require one the answer will be yes as long as there is enough value.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-rabbitmq/versions/3.5.0

**Pull request merged**
