### PR TITLE
Update and complete README

### PR DESCRIPTION
**Pull request by hillaryfraley**
## Pull Request Checklist

**Is this in reference to an existing issue?**
No

#### General

- [ ] Update Changelog following the conventions laid out [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [x] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### Purpose
Standardize readme according to https://github.com/sensu-plugins/community/pull/134

#### Known Compatibility Issues
None

### CODE REVIEW

**Comment by hillaryfraley** [comment]
Need to add usage examples. I could not get this plugin to install to retrieve them myself.

```
hillaryfraley@Hillarys-Sensu-MacBook-Pro ~ % sudo sensu-install -p rabbitmq --verbose
[SENSU-INSTALL] installing Sensu plugins ...
[SENSU-INSTALL] provided Sensu plugins: ["rabbitmq"]
[SENSU-INSTALL] compiled Sensu plugin gems: ["sensu-plugins-rabbitmq"]
[SENSU-INSTALL] determining if Sensu gem 'sensu-plugins-rabbitmq' is already installed ...
[SENSU-INSTALL] gem list -i sensu-plugins-rabbitmq
false
[SENSU-INSTALL] Sensu gem 'sensu-plugins-rabbitmq' has not been installed
[SENSU-INSTALL] Sensu plugin gems to be installed: ["sensu-plugins-rabbitmq"]
[SENSU-INSTALL] installing Sensu gem 'sensu-plugins-rabbitmq'
[SENSU-INSTALL] gem install sensu-plugins-rabbitmq --no-document --verbose
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=sensu-plugins-rabbitmq
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/quick/Marshal.4.8/sensu-plugins-rabbitmq-8.0.0.gemspec.rz
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=amq-protocol,bunny,carrot-top,inifile,rest-client,ruby_dig,sensu-plugin,stomp
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=http-cookie,mime-types,netrc
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=json,mixlib-cli
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=domain_name
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=mime-types-data
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=unf
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=unf_ext
200 OK
GET https://api.rubygems.org/quick/Marshal.4.8/unf_ext-0.0.7.6.gemspec.rz
200 OK
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/.document
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/.gitignore
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/.travis.yml
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/CHANGELOG.md
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/Gemfile
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/LICENSE.txt
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/README.md
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/Rakefile
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/ext/unf_ext/extconf.rb
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/ext/unf_ext/unf.cc
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/ext/unf_ext/unf/normalizer.hh
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/ext/unf_ext/unf/table.hh
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/ext/unf_ext/unf/trie/char_stream.hh
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/ext/unf_ext/unf/trie/node.hh
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/ext/unf_ext/unf/trie/searcher.hh
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/ext/unf_ext/unf/util.hh
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/lib/unf_ext.rb
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/lib/unf_ext/version.rb
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/test/helper.rb
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/test/normalization-test.txt
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/test/test_unf_ext.rb
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/unf_ext.gemspec
Building native extensions. This could take a while...
current directory: /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/ext/unf_ext
/opt/sensu/embedded/bin/ruby -r ./siteconf20191206-14319-wfn10h.rb extconf.rb
checking for -lstdc++... no
creating Makefile
current directory: /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/ext/unf_ext
make "DESTDIR=" clean
current directory: /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6/ext/unf_ext
make "DESTDIR="
compiling unf.cc
linking shared-object unf_ext.bundle
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [unf_ext.bundle] Error 1
ERROR:  Error installing sensu-plugins-rabbitmq:
	ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
make failed, exit code 2

Gem files will remain installed in /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.6 for inspection.
Results logged to /opt/sensu/embedded/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-16/2.4.0/unf_ext-0.0.7.6/gem_make.out
[SENSU-INSTALL] failed to install Sensu gem 'sensu-plugins-rabbitmq'
[SENSU-INSTALL] please take note of any failure messages above
[SENSU-INSTALL] make sure you have build tools installed (e.g. gcc)
[SENSU-INSTALL] trying to determine the Sensu plugin homepage for sensu-plugins-rabbitmq ...
homepage: https://github.com/sensu-plugins/sensu-plugins-rabbitmq
```

**Comment by jspaleta** [comment]
hey!
Was this ready for merge or is this still a work in progress?
Do you need help getting a working build?

**Comment by hillaryfraley** [comment]
Hi @jspaleta ! WIP right now. Aaron put something together that should help me get a working build, but if I can't get it working, I'll follow up with you. Thank you.

**Comment by hillaryfraley** [comment]
@jspaleta this one should be ready for review now!

The error I had was because I didn't have a library installed on my mac. Aaron got me going in a vagrant box so I could get the usage examples. He mentioned this probably isn't something that needs to be in the readme. wdyt?

**Pull request merged**
